apiVersion: apps/v1
kind: Deployment
metadata:
  name: kctf-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kctf-operator
  template:
    metadata:
      labels:
        name: kctf-operator
    spec:
      serviceAccountName: kctf-operator
      containers:
        - name: kctf-operator
          # TODO: Replace this with the built image name
          image: quay.io/aliciafmachado/kctf-operator:v0.0.4
          command:
          - kctf-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kctf-operator"
